### ISSUE TITLE
Communication Cost in the Cost Model

### ISSUE THREAD

**Issue by yangdsh** [microsoft/nnscaler#3]
Thank you for sharing nnScaler. I have two questions about the communication cost.

1. In cost_model.py, get_comm_cost() only calculates all-reduce and get_pair_reshard_cost() calculates other resharding cost. I am wondering why they are not combined as a single function.
2. In spmd.py, when modeling the cost for ILP, get_comm_cost() is divided by dp_size while get_pair_reshard_cost() is not divided by dp_size. Why are they handled differently?

Thank you for your reply!

**Comment by lynex** [comment]
Thank you for your interest in our paper & project!

  1. The functions **get_comm_cost()** and **get_pair_reshard_cost()** could indeed be combined, but they are currently separate to better align with the existing code structure in Alpa. This separation allows for clearer modularity and easier maintenance.
  2. Thank you for pointing out the discrepancy. We acknowledge this inconsistency, and we will address the bug. However, this issue does not impact our results in paper because **dp_size** is **1** in various evaluations due to the models' large sizes.
