### ISSUE TITLE
Questions for OOM During Mem Profile

### ISSUE THREAD

**Issue by SaoXiaoPiZhuPi** [microsoft/nnscaler#7]
Thank you very much for your excellent work. Recently, I tested compiling the Llama3-70B model using nnScaler on 32 A40 GPUs, each with 46GB of memory. During the profiling process, I encountered an OOM (Out of Memory) issue. Although nnScaler has a penalty setting with a default value for such cases, is there any way to leverage multiple GPUs during the profiling phase to avoid OOM? Besides, the profiling phase only use the GPUs on node0, maybe we can leverage all the GPUs to accelarate profiling phase

**Comment by zyeric** [comment]
Could you provide the detailed OOM message so that I understand your problem more clearly?

Based on my [explanation](https://github.com/microsoft/nnscaler/issues/6#issuecomment-2426839318) in another issue, autodist profiles all possible partitions of an operator. If an OMM is raised, then this partition is valid and we should exclude it from the generated partition plan. Adding more device helps to reduce the profiling time but will not avoid OOMs.

Thanks for your suggestion, we may add the distributed profiling in the near release :)

**Comment by SaoXiaoPiZhuPi** [comment]
Thanks again for your help. The error message is showing below:
```
fail to profile FwOp83-()(name=mul, inputs=(t27054(p197,(1, 131072, 28672),d(),v(0/1)), t27056(p201,(1, 131072, 28672),d(),v(0/1))), outputs=(t27057(p203,(1, 131072, 28672),d(),v(0/1)),)), use default values
Traceback (most recent call last):
  File "/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/qinghe/nnscaler-main/nnscaler/profiler/database.py", line 343, in profile
    profile(node, fn, shapes, dtypes, requires_grads, values, **kwargs)
  File "/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/qinghe/nnscaler-main/nnscaler/profiler/database.py", line 253, in profile
    run_step(func, tensors, train_kwargs, backward=require_backward)
  File "/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/qinghe/nnscaler-main/nnscaler/profiler/database.py", line 199, in run_step
    torch.autograd.backward(outputs, grads)
  File "/opt/conda/envs/andy/nnscaler/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/opt/conda/envs/andy/nnscaler/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.00 GiB. GPU  has a total capacity of 44.56 GiB of which 1.80 GiB is free. Process 3762519 has 458.00 MiB memory in use. Process 3785675 has 42.30 GiB memory in use. Of the allocated memory 42.00 GiB is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```

**Comment by zyeric** [comment]
According to the error, the operator is too large to place into a single device. If the datatype is bf16 or fp16, each input / output tensor is 131072 * 28672 * 2 = 7GB. Since AutoDist profiles the forward and backward computation of a operator, it takes about 3 * 7 * 2 = 42 GB. I think in the generated plan, this `mul` operator will be partitioned along the 2nd dim or 3rd dim.

**Comment by SaoXiaoPiZhuPi** [comment]
Thank you for your patient response. I wonder if there are any plans to use multiple devices to profile large operators, or to split large operators so that a single device can complete the profiling of large operators (like the ```mul``` mentioned before).

**Comment by SaoXiaoPiZhuPi** [comment]
Thank you for the detailed explanation, and I get it now. I had some misunderstandings about the profile phase and generate phase previously.
